"""c15 -- emit results/manuscript_table.tex from the audit JSONs.

Generated, never hand-edited, for the same reason ARCHITECTURE.md is: a table
transcribed by hand drifts from the run it claims to report.

Emits four standalone tables:
  tab:causality      unstable-ReLU count vs LayerNorm bracket vs bound, which is
                     the evidence that the causal order runs ReLU -> bound and
                     not LayerNorm -> bound
  tab:nonmonotone    the radii where the bound moves the wrong way
  tab:audit          replay / falsification / coverage per radius
  tab:z3             the exact-SMT primitive results

Requires booktabs and siunitx.
"""
import os, json, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
OUT = os.path.join(RES, "manuscript_table.tex")

sys.path.insert(0, os.path.join(ROOT, "audit"))
import c2425_data as CD  # noqa: E402  (c24/c25 write one file per cell)


def load(n):
    p = os.path.join(RES, n)
    return json.load(open(p)) if os.path.exists(p) else None


lns, aud, z3r, base = (load("c14_ln_sweep.json"), load("c14_audit.json"),
                       load("c14_z3.json"), load("baseline.json"))
L = []
a = L.append

a("% Generated by audit/make_manuscript_table.py -- do not edit by hand.")
a("% Regenerate after any run: python audit/make_manuscript_table.py")
a("% Requires: \\usepackage{booktabs,siunitx}")
a("")

# ----------------------------------------------------------- causality table
if lns:
    def site(row):
        return [x for x in row["sites"] if x["layer"] == 1 and x["site"] == "ln2"][0]

    rows = [r for r in lns["rows"] if 2e-3 <= r["rho"] <= 3e-2]
    zero_at = lns["cliff"]["margin_bound_first_nonnegative_at_rho"]
    zero_row = next(r for r in lns["rows"] if r["rho"] == zero_at)
    # first radius at which the LayerNorm bracket is no longer tight
    cliff_row = next((r for r in lns["rows"]
                      if site(r)["spread_ratio_max"] > 10.0), None)
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Failure causality in the monolithic margin bound. The bound "
      "crosses zero at $\\rho\\approx\\num{%.5f}$, where the LayerNorm variance "
      "bracket is still essentially tight (spread \\num{%.2f}). The bracket only "
      "leaves that regime at $\\rho\\ge\\num{%.5f}$, by which point the bound has "
      "already reached \\num{%.3e}. The unstable-ReLU count is therefore the "
      "driver and the LayerNorm cliff a downstream consequence. Bounds are "
      "\\emph{unsplit} (no branch-and-bound); the certificate reaches "
      "$\\rho=0.04$ only by splitting into 2048 boxes.}"
      % (zero_at, site(zero_row)["spread_ratio_max"],
         cliff_row["rho"], cliff_row["margin_bound"]))
    a("\\label{tab:causality}")
    a("\\begin{tabular}{S[table-format=1.5] S[table-format=+1.3e2] "
      "S[table-format=3.0] S[table-format=1.3e2]}")
    a("\\toprule")
    a("{$\\rho$} & {margin bound} & {unstable ReLUs} & {LN spread (max)} \\\\")
    a("\\midrule")
    for r in rows:
        s = site(r)
        a(f"{r['rho']:.5f} & {r['margin_bound']:+.3e} & "
          f"{s['unstable_relus']:d} & {s['spread_ratio_max']:.3e} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a(f"\\\\[2pt]\\footnotesize Unstable ReLUs out of {site(rows[0])['of_total']} "
      "at the layer-1 \\texttt{ln2} MLP input.")
    a("\\end{table}")
    a("")

    # ------------------------------------------------------ non-monotone table
    viol = []
    allr = lns["rows"]
    for i in range(1, len(allr)):
        if allr[i]["margin_bound"] < allr[i - 1]["margin_bound"]:
            viol.append((allr[i - 1], allr[i]))
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{The bound is not monotone in the perturbation radius. "
      "\\texttt{promote\\_E\\_topk} and \\texttt{compact} are radius-dependent "
      "heuristics, so a larger box can receive a more favourable promotion. Any "
      "radius sweep must be plotted raw rather than fitted.}")
    a("\\label{tab:nonmonotone}")
    a("\\begin{tabular}{S[table-format=1.5] S[table-format=1.3e2] "
      "S[table-format=1.5] S[table-format=1.3e2]}")
    a("\\toprule")
    a("\\multicolumn{2}{c}{smaller radius} & \\multicolumn{2}{c}{larger radius} \\\\")
    a("\\cmidrule(lr){1-2}\\cmidrule(lr){3-4}")
    a("{$\\rho$} & {bound} & {$\\rho$} & {bound} \\\\")
    a("\\midrule")
    for lo, hi in viol:
        a(f"{lo['rho']:.5f} & {lo['margin_bound']:.3e} & "
          f"{hi['rho']:.5f} & {hi['margin_bound']:.3e} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a(f"\\\\[2pt]\\footnotesize {len(viol)} monotonicity violations across "
      f"{len(allr)} radii spanning "
      f"$[\\num{{{lns['config']['rho_lo']}}}, \\num{{{lns['config']['rho_hi']}}}]$.")
    a("\\end{table}")
    a("")

# --------------------------------------------------------------- audit table
if aud:
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Independent audit of the monolithic margin certificate. The "
      "replay reproduces the baseline verdict at every radius. Coverage is the "
      "fraction of \\num{20000} uniform points in $[-\\rho,\\rho]^4$ landing in "
      "some discharged box, so $1.0$ confirms the per-box claims tile the threat "
      "set. $\\Delta$ is the largest amount by which any sampled point exceeded "
      "the bound claimed for its own box; it must remain negative. The final "
      "column is a from-scratch interval engine, which closes nothing at any "
      "radius.}")
    a("\\label{tab:audit}")
    a("\\begin{tabular}{S[table-format=1.3] c c S[table-format=4.0] "
      "S[table-format=1.4] S[table-format=+2.4] S[table-format=+1.3e2] c}")
    a("\\toprule")
    a("{$\\rho$} & proved & agrees & {boxes} & {coverage} & "
      "{max true margin} & {$\\Delta$} & {IBP closed} \\\\")
    a("\\midrule")
    for r, v in aud["per_rho"].items():
        f, c, i = v["falsification"], v["coverage"], v["independent_ibp"]
        mt = f["max_true_margin_found"]
        dl = f["max_true_minus_claimed_bound"]
        mts = "{--}" if mt == float("-inf") else f"{mt:+.4f}"
        dls = "{--}" if dl == float("-inf") else f"{dl:+.3e}"
        yn = lambda b: "yes" if b else "no"
        a(f"{float(r):.3f} & {yn(v['prover_proved'])} & "
          f"{yn(v['replay_agrees_with_baseline'])} & "
          f"{v['discharged_boxes']:d} & {c['random_point_coverage']:.4f} & "
          f"{mts} & {dls} & "
          f"{i['boxes_closed']}/{i['boxes_attempted']} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a(f"\\\\[2pt]\\footnotesize {aud['config']['samples_per_box']} samples per "
      f"box plus {aud['config']['pgd_steps']}-step PGD confined to each box; "
      f"\\num{{{sum(v['discharged_boxes'] for v in aud['per_rho'].values())}}} "
      f"boxes total, \\SI{{{aud['runtime_sec']:.0f}}}{{\\second}}. "
      "$\\rho=0.06$ discharges no boxes because the prover fails there.")
    a("\\end{table}")
    a("")

# ------------------------------------------------------------------ z3 table
if z3r:
    s = z3r["summary"]
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Exact SMT audit of the prover's primitives (z3~%s, "
      "\\SI{%d}{\\second} budget, $\\rho=%s$). \\texttt{unknown} is a solver "
      "timeout, never a refutation. The tightness query is the one that detects "
      "the patched readout bug: the original $\\max_u L_u - \\min_j L_j$ remains "
      "a \\emph{sound} upper bound, so a soundness check passes on it, and only "
      "tightness exposes the \\num{11.7}-logit inflation.}"
      % (z3r["config"]["z3_version"], z3r["config"]["timeout_ms"] // 1000,
         z3r["config"]["rho"]))
    a("\\label{tab:z3}")
    a("\\begin{tabular}{l l c c}")
    a("\\toprule")
    a("check & expected & conclusive & passed \\\\")
    a("\\midrule")
    ms, mt = s["margin_soundness"], s["margin_tightness"]
    a(f"margin readout, soundness & \\texttt{{unsat}} & "
      f"{ms['conclusive']}/{ms['attempted']} & {ms['passed']}/{ms['attempted']} \\\\")
    a(f"margin readout, tightness & \\texttt{{sat}} & "
      f"{mt['passed']}/{mt['attempted']} & {mt['passed']}/{mt['attempted']} \\\\")
    for k, lab in (("relu", "ReLU containment"),
                   ("layernorm", "LayerNorm containment")):
        t = s[k]
        a(f"{lab} & \\texttt{{unsat}} & {t['conclusive']}/{t['attempted']} & "
          f"{t['passed']}/{t['attempted']} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a("\\end{table}")
    a("")

crown, c16 = load("c16_crown.json"), load("c16.json")

# ------------------------------------------------------------- CROWN vs prover
if crown:
    r0 = crown["rows"][0]
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Where the independent linear-relaxation prover loses, at "
      "$\\rho=\\num{%g}$. \\textsc{true} is the attained width under dense "
      "sampling of the exact model, a lower bound on what any sound method can "
      "report. The CROWN engine keeps the four steering coefficients exactly and "
      "tracks the prover through the first LayerNorm, then diverges at "
      "\\texttt{%s}, where softmax uncertainty enters as interval coefficients "
      "on $V$. The loss compounds through layer~1. It closes no box that the "
      "prover closes, so the end-to-end cross-check remains open.}"
      % (r0["rho"], crown["diagnosis"]["first_divergent_stage"].replace("_", "\\_")))
    a("\\label{tab:crown}")
    a("\\begin{tabular}{l S[table-format=1.3e2] S[table-format=1.3e2] "
      "S[table-format=1.3e2] S[table-format=2.2] S[table-format=1.2e2]}")
    a("\\toprule")
    a("stage & {true} & {zonotope} & {CROWN} & {zono/true} & {CROWN/true} \\\\")
    a("\\midrule")
    for s in r0["stages"]:
        a(f"\\texttt{{{s['stage'].replace('_', chr(92) + '_')}}} & {s['true']:.3e} & "
          f"{s['hzono']:.3e} & {s['crown']:.3e} & "
          f"{s['hzono_over_true']:.2f} & {s['crown_over_true']:.2e} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a("\\end{table}")
    a("")

# ------------------------------------------------------ prompt distribution
if c16:
    d = c16["distribution"]
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{From a single anchor to a prompt distribution. Certifying each "
      "anchor separately is exact but costs $N$ proofs and the guarantee is the "
      "minimum over anchors. Replacing the nominal streams by a single box hull "
      "gives one proof for all $N$ at the cost of containing streams no prompt "
      "produces.}")
    a("\\label{tab:distribution}")
    a("\\begin{tabular}{l l}")
    a("\\toprule")
    a("anchor & {max certified $\\rho$} \\\\")
    a("\\midrule")
    for p, v in d["per_prompt"].items():
        rr = v["max_certified_rho"]
        a(f"prompt {p} & {rr if rr is not None else '{none}'} \\\\")
    a("\\midrule")
    wc = d["worst_case_over_prompts"]
    hb = d["hull"]["max_certified_rho"]
    a(f"worst case over anchors & {wc if wc is not None else '{none}'} \\\\")
    a(f"box hull (one proof) & {hb if hb is not None else '{none}'} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    tax = d["conservation_tax"]["ratio"]
    if tax:
        a(f"\\\\[2pt]\\footnotesize Conservation tax \\num{{{tax:.2f}}}$\\times$ "
          "in radius for a single proof covering all anchors.")
    else:
        a("\\\\[2pt]\\footnotesize The hull certified nothing on the grid: it is "
          "a full-dimensional box over the residual stream, the regime the "
          "baseline already reports as catastrophic.")
    a("\\end{table}")
    a("")

    b = c16["branching"]; v = b["verdict"]
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Branching rule. Unstable ReLUs drive the bound explosion, but "
      "branch-and-bound splits in $\\alpha$ space, so the targeted rule picks "
      "the coordinate whose bisection most reduces layer-0 unstable-ReLU mass "
      "rather than the widest coordinate.%s}"
      % ("" if v["improved"] else
         " It does not improve the certified radius: with only four steering "
         "coordinates the widest-coordinate rule already removes comparable "
         "unstable-ReLU mass."))
    a("\\label{tab:branching}")
    a("\\begin{tabular}{l l S[table-format=4.0]}")
    a("\\toprule")
    a("rule & {max certified $\\rho$} & {seconds} \\\\")
    a("\\midrule")
    for r in ("widest", "relu_guided"):
        rr = b[r]["max_certified_rho"]
        a(f"\\texttt{{{r.replace('_', chr(92) + '_')}}} & "
          f"{rr if rr is not None else '{none}'} & {b[r]['seconds']:.0f} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a("\\end{table}")
    a("")

c17 = load("c17.json")
if c17:
    ab = c17["softmax_ablation"]
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Softmax relaxation ablation at layer-0 attention, "
      "$\\rho=\\num{%g}$. Replacing an interval enclosure of the attention "
      "probabilities with a full Shi-style linear relaxation (exp "
      "secant/tangent, reciprocal secant/tangent, McCormick product) reduces "
      "the gap by \\SI{%.1f}{\\percent}. Softmax relaxation quality is "
      "therefore \\emph{not} the bottleneck: the two-sided linear-bound "
      "representation must relax the product $p\\cdot v$, whereas a zonotope "
      "carries $p$ and $v$ over shared noise symbols and keeps the first-order "
      "cross terms exactly.}"
      % (ab["rho"], 100 * (1 - ab["modes"]["linear"]["over_true"]
                           / ab["modes"]["interval"]["over_true"])))
    a("\\label{tab:softmax}")
    a("\\begin{tabular}{l S[table-format=1.3e2] S[table-format=2.2]}")
    a("\\toprule")
    a("method & {width} & {$\\times$ attainable} \\\\")
    a("\\midrule")
    a(f"attained (sampling) & {ab['true_width']:.3e} & 1.00 \\\\")
    a(f"hybrid zonotope & {ab['zonotope']['width']:.3e} & "
      f"{ab['zonotope']['over_true']:.2f} \\\\")
    for k, lab in (("interval", "CROWN, interval softmax"),
                   ("linear", "CROWN, linear softmax")):
        m = ab["modes"][k]
        a(f"{lab} & {m['width']:.3e} & {m['over_true']:.2f} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a("\\end{table}")
    a("")

    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Width scaling of the relaxation on \\emph{randomly "
      "initialised} transformers. These measure how the relaxation behaves as "
      "$d_{\\text{model}}$ grows, not certified radius on a trained model. "
      "Amplification is final stream width over input width. Unstable-ReLU "
      "fraction saturates at $1/T=0.2$ because only the final token is "
      "perturbed, so $0.200$ means every unit at that position is unstable.}")
    a("\\label{tab:widthscaling}")
    a("\\begin{tabular}{S[table-format=3.0] S[table-format=1.4] "
      "S[table-format=1.3e2] S[table-format=1.3] S[table-format=1.3e2]}")
    a("\\toprule")
    a("{$d_{\\text{model}}$} & {$\\rho$} & {amplification} & "
      "{L1 unstable frac} & {L1 LN spread} \\\\")
    a("\\midrule")
    for r in c17["width_scaling"]["rows"]:
        l1 = r["layers"][-1]
        a(f"{r['d_model']} & {r['rho']:.4f} & {r['amplification']:.3e} & "
          f"{l1['unstable_frac']:.3f} & {l1['ln2_spread']:.3e} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    ps = c17["prompt_sweep"]
    a(f"\\\\[2pt]\\footnotesize Anchor sweep: {ps['n_certified']}/{ps['n']} "
      f"anchors certified at $\\rho={ps['rho']}$ with a "
      f"{ps['max_boxes']}-box budget.")
    a("\\end{table}")
    a("")

c18d, c19d = load("c18.json"), load("c19.json")
if c18d:
    S = c18d["scaling_summary"]
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Relaxation gap (bound width divided by attained width) against "
      "$d_{\\text{model}}$, on randomly initialised transformers at "
      "$\\rho=\\num{1e-4}$. The gap, not the bound width, is the right metric: "
      "a variant can shrink its bound merely by being a less sensitive "
      "function, and attained sensitivity here is near-identical across "
      "variants (log-log slope about $-0.1$). Replacing LayerNorm's "
      "data-dependent scale with a fixed affine one removes about eight orders "
      "of magnitude at $d=256$; adding a smooth activation on top buys "
      "nothing. The wall is delayed, not removed: the exponent falls from "
      "11.12 to 2.46, which is still super-linear.}")
    a("\\label{tab:variants}")
    a("\\begin{tabular}{l S[table-format=1.2e2] S[table-format=1.2e2] "
      "S[table-format=1.2e2] S[table-format=1.2e2] S[table-format=2.2]}")
    a("\\toprule")
    a("variant & {$d{=}32$} & {$d{=}64$} & {$d{=}128$} & {$d{=}256$} & "
      "{gap slope} \\\\")
    a("\\midrule")
    for v in ("standard", "fixnorm", "fixnorm_tanh"):
        if v not in S:
            continue
        g = S[v]["relaxation_gap_by_width"]
        cells = " & ".join(f"{g[str(k)]:.2e}" for k in (32, 64, 128, 256)
                           if str(k) in g)
        a(f"\\texttt{{{v.replace('_', chr(92) + '_')}}} & {cells} & "
          f"{S[v]['log_log_slope_gap']:.2f} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a("\\end{table}")
    a("")

if c19d:
    S9, cfg = c19d["summary"], c19d["config"]
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Trainability at $d_{\\text{model}}=%d$: %d steps, batch %d, "
      "lr %g, %d seeds, identical batch stream across variants. The frozen "
      "scale is calibrated once before training and never receives gradient. "
      "\\textbf{The task saturates} -- every variant reaches 100\\%% accuracy "
      "-- so this shows the absence of a penalty here and cannot bound the "
      "penalty on a harder task.}"
      % (cfg["d_model"], cfg["steps"], cfg["batch"], cfg["lr"], cfg["seeds"]))
    a("\\label{tab:trainability}")
    a("\\begin{tabular}{l S[table-format=1.4] S[table-format=1.2e2] "
      "S[table-format=1.3] S[table-format=2.1]}")
    a("\\toprule")
    a("variant & {test acc} & {test CE} & {trained gap} & {gap gain} \\\\")
    a("\\midrule")
    for v in ("standard", "fixnorm", "fixnorm_tanh"):
        s = S9[v]
        a(f"\\texttt{{{v.replace('_', chr(92) + '_')}}} & "
          f"{s['test_accuracy_mean']:.4f} & {s['test_ce_mean']:.2e} & "
          f"{s['trained_relaxation_gap_median']:.3f} & "
          f"{s['gap_improvement_vs_standard']:.1f} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a("\\end{table}")
    a("")


c20d = load("c20.json")
if c20d:
    S0, cfg0, tk = c20d["summary"], c20d["config"], c20d["config"]["task"]
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Expressivity boundary at $d_{\\text{model}}=%d$ on a "
      "\\emph{non-saturated} two-hop routing task (%d distractor features, "
      "$T=%d$, vocabulary %d, %d seeds). Baseline accuracy \\num{%.4f} sits "
      "inside the discriminatory band, and a penalty appears that the "
      "saturated task of Table~\\ref{tab:trainability} reported as exactly "
      "zero. Task saturation does not reduce a penalty, it hides one.}"
      % (cfg0["d_model"], tk["distractor_features"], tk["SEQ_LEN"],
         tk["VOCAB"], cfg0["seeds"], c20d["baseline_accuracy"]))
    a("\\label{tab:expressivity}")
    a("\\begin{tabular}{l S[table-format=1.4] S[table-format=+1.4] "
      "S[table-format=1.4] S[table-format=2.3] S[table-format=2.1]}")
    a("\\toprule")
    a("variant & {test acc} & {$\\Delta$} & {test CE} & {trained gap} & "
      "{gap gain} \\\\")
    a("\\midrule")
    for v in ("standard", "fixnorm", "fixnorm_tanh"):
        s0 = S0[v]
        nm = v.replace("_", "\\_")
        a(f"\\texttt{{{nm}}} & {s0['test_accuracy_mean']:.4f} & "
          f"{s0['accuracy_delta_vs_standard']:+.4f} & "
          f"{s0['test_ce_mean']:.4f} & "
          f"{s0['trained_relaxation_gap_median']:.3f} & "
          f"{s0['gap_improvement_vs_standard']:.1f} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    a("\\\\[2pt]\\footnotesize Pareto exchange: "
      f"\\num{{{S0['fixnorm']['gap_improvement_vs_standard']:.1f}}}"
      "$\\times$ verifiability for "
      f"\\num{{{abs(S0['fixnorm']['accuracy_delta_vs_standard'])*100:.1f}}}"
      " accuracy points. \\texttt{fixnorm\\_tanh} is dominated.")
    a("\\end{table}")
    a("")

c21d = load("c21.json")
if c21d:
    S1, cfg1, tr = c21d["summary"], c21d["config"], c21d["trend"]
    band_note = ("" if tr.get("both_widths_in_band", True) else
                 " \\textbf{The trend is not interpretable as a capacity "
                 "effect: the baseline leaves the discriminatory band, and a "
                 "saturated baseline reports a shrinking penalty whether or "
                 "not one exists.}")
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Pareto exchange against capacity: %d seeds per cell, %d "
      "training steps, same non-saturated two-hop task. Intervals are 95\\%% "
      "on the mean.%s}"
      % (cfg1["seeds"], cfg1["steps"], band_note))
    a("\\label{tab:pareto}")
    a("\\begin{tabular}{S[table-format=2.0] l S[table-format=1.4] "
      "S[table-format=1.4] S[table-format=2.3] c}")
    a("\\toprule")
    a("{$d_{\\text{model}}$} & variant & {test acc} & {SEM} & {gap} & "
      "{in band} \\\\")
    a("\\midrule")
    for w in cfg1["widths"]:
        r = S1[str(w)]
        for v in cfg1["variants"]:
            s = r[v]
            nm = v.replace("_", "\\_")
            a(f"{w} & \\texttt{{{nm}}} & {s['test_accuracy_mean']:.4f} & "
              f"{s['test_accuracy_sem']:.4f} & "
              f"{s['relaxation_gap_median']:.3f} & "
              f"{'yes' if r['baseline_in_band'] else 'no'} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    if tr:
        w0, w1 = str(cfg1["widths"][0]), str(cfg1["widths"][-1])
        a("\\\\[2pt]\\footnotesize Penalty "
          f"\\num{{{tr['penalty_points'][w0]:.2f}}} to "
          f"\\num{{{tr['penalty_points'][w1]:.2f}}} points; verifiability gain "
          f"\\num{{{tr['gap_gain'][w0]:.1f}}}$\\times$ to "
          f"\\num{{{tr['gap_gain'][w1]:.1f}}}$\\times$.")
    a("\\end{table}")
    a("")

c23d = load("c23.json")
if c23d:
    S3, cfg3, D3, tr3 = (c23d["summary"], c23d["config"], c23d["data"],
                         c23d["trend"])
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Expressivity cost of a data-independent normalizer on "
      "natural text. Character-level language modelling on %s "
      "(\\num{%d} characters, %d-symbol vocabulary), context "
      "$T=%d$, %d seeds per cell, %d steps. Perplexity is raw and held out on "
      "\\num{%d} next-character predictions; unlike the accuracy tasks it has "
      "no ceiling, so no cell is confounded by saturation. The gap is the "
      "post-hoc hybrid-zonotope bound width divided by the attained width at "
      "$\\rho=\\num{%g}$.}"
      % (D3["name"], D3["chars"], D3["vocab"], cfg3["seq_len"], cfg3["seeds"],
         cfg3["steps"], cfg3["val_tokens"], cfg3["rho"]))
    a("\\label{tab:language}")
    a("\\begin{tabular}{S[table-format=2.0] l S[table-format=2.4] "
      "S[table-format=1.4] S[table-format=4.3] c}")
    a("\\toprule")
    a("{$d_{\\text{model}}$} & variant & {held-out ppl} & {SEM} & {gap} & "
      "{vs.\\ standard} \\\\")
    a("\\midrule")

    def _verdict(r):
        # signed fixnorm - standard: a CI strictly below zero means fixnorm is
        # the better model, which is not the same as "no significant penalty"
        lo_, hi_ = r["ppl_penalty_ci95"]
        if lo_ > 0:
            return "penalty"
        if hi_ < 0:
            return "better"
        return "n.s."

    for w in cfg3["widths"]:
        r = S3[str(w)]
        for v in cfg3["variants"]:
            s = r[v]
            nm = v.replace("_", "\\_")
            sig = "{--}" if v == "standard" else _verdict(r)
            a(f"{w} & \\texttt{{{nm}}} & {s['val_ppl_mean']:.4f} & "
              f"{s['val_ppl_sem']:.4f} & "
              f"{s['relaxation_gap_median']:.3f} & {sig} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    w0, w1 = str(cfg3["widths"][0]), str(cfg3["widths"][-1])
    a("\\\\[2pt]\\footnotesize Perplexity penalty "
      f"\\num{{{S3[w0]['ppl_penalty_pct']:.2f}}}\\% to "
      f"\\num{{{S3[w1]['ppl_penalty_pct']:.2f}}}\\%; verifiability gain "
      f"\\num{{{S3[w0]['gap_gain']:.1f}}}$\\times$ to "
      f"\\num{{{S3[w1]['gap_gain']:.1f}}}$\\times$ across "
      f"$d_{{\\text{{model}}}}={w0}$ to ${w1}$. Maximum containment violation "
      f"\\num{{{c23d['soundness']['max_containment_violation']:.1e}}} "
      f"(float noise; the bound is sound on every run).")
    a("\\end{table}")
    a("")

# ------------------------------------------------------------------ c24 depth
# c24 writes one file per cell, not a unified JSON, so this reads the raw cells.


def _g(x):
    """Gap -> \\num{}, or a literal dash. Gaps here span 1.18 to 5.8e22."""
    if x is None:
        return "{--}"
    return f"\\num{{{x:.3g}}}"


def _u(x):
    return "{--}" if x is None else f"{int(x)}"


c24 = CD.load_c24()
if c24:
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Depth and width scaling of the relaxation gap on "
      "character-level TinyShakespeare, $T=8$, 3 seeds per cell, "
      "\\num{3000} steps, $\\rho=\\num{1e-4}$. Gap is the post-hoc "
      "hybrid-zonotope bound width over the attained width; medians, because "
      "run-to-run spread at fixed configuration reaches "
      f"\\num{{{CD.SEED_NOISE}}}$\\times$. Cells marked {{--}} were not "
      "verified: $d=512$ lies outside the verification subgrid and "
      "$L=12$, $d=512$ diverged on every seed. A gap above "
      f"\\num{{{CD.GAP_MEANINGFUL:.0g}}} means the bound is not informative, "
      "so no gain ratio is quoted. The pairing column flags cells whose two "
      "arms trained on different devices, where the measured CUDA/CPU "
      "perplexity drift (\\num{0.62}\\%) is comparable to the penalty being "
      "reported and the perplexity comparison is therefore not valid.}")
    a("\\label{tab:depthwidth}")
    a("\\begin{tabular}{S[table-format=2.0] S[table-format=3.0] l l l l l}")
    a("\\toprule")
    a("{$L$} & {$d_{\\text{model}}$} & {standard gap} & {unstable} & "
      "{fixnorm gap} & {unstable} & {ppl pairing} \\\\")
    a("\\midrule")
    # NB: do not name these L / d -- `L` is the module-level output line list.
    _rows = [(_L, _d) for _L in (2, 4, 8, 12) for _d in (64, 128, 256, 512)
             if (_L, _d, "standard") in c24 or (_L, _d, "fixnorm") in c24]
    for (_L, _d) in _rows:
        s = c24.get((_L, _d, "standard"), {})
        f = c24.get((_L, _d, "fixnorm"), {})
        a(f"{_L} & {_d} & {_g(s.get('gap_median'))} & "
          f"{_u(s.get('unstable_median'))}"
          f" & {_g(f.get('gap_median'))} & {_u(f.get('unstable_median'))}"
          f" & {CD.c24_pairing(c24, _L, _d)} \\\\")
    a("\\bottomrule")
    a("\\end{tabular}")
    _f4 = [c24.get((4, d, "fixnorm"), {}).get("gap_median") for d in
           (64, 128, 256)]
    if all(x is not None for x in _f4):
        a("\\\\[2pt]\\footnotesize The fixnorm row at $L=4$ reads "
          f"\\num{{{_f4[0]:.2f}}}, \\num{{{_f4[1]:.1f}}}, "
          f"\\num{{{_f4[2]:.1f}}} across $d=64,128,256$: a factor "
          f"\\num{{{_f4[1]/_f4[0]:.0f}}} between the first two widths and "
          f"\\num{{{_f4[2]/_f4[1]:.2f}}} between the last two. Three widths "
          "are consistent with an onset between $d=64$ and $d=128$ and are "
          "inconsistent with a smooth power law, but they cannot localise "
          "the onset; no width exponent is fitted.")
    a("\\end{table}")
    a("")

# ------------------------------------------------------- c25 certified training
cert = CD.load_c25("c25_certified_parts")
ctrl = CD.load_c25("c25_control_parts")
if cert and ctrl:
    _lrs = sorted({k[3] for k in ctrl if k[:2] == (2, 32)})
    a("\\begin{table}[t]")
    a("\\centering")
    a("\\caption{Certified training versus ordinary training, "
      "$L=2$, $d_{\\text{model}}=32$, $\\rho=\\num{0.02}$, "
      "\\num{3000} steps, 3 seeds per arm. Control is the identical recipe "
      "with the robust term disabled. The certified arm optimises an "
      "interval-bound upper bound on the loss; the gap column is still "
      "measured post hoc by the hybrid-zonotope prover, so the two arms are "
      "certified by the same engine. Standard diverges under certified "
      "training at every learning rate, so it has no certified arm.}")
    a("\\label{tab:certified}")
    a("\\begin{tabular}{l l S[table-format=1.3] l l l l}")
    a("\\toprule")
    a("{lr} & variant & {arm} & {converged} & {ppl (SEM)} & "
      "{gap median} & {gap range} \\\\")
    a("\\midrule")
    for lr in _lrs:
        for v in ("fixnorm", "standard"):
            for nm, src in (("control", ctrl), ("certified", cert)):
                A = CD.arm(src.get((2, 32, v, lr), []))
                if not A["n_total"]:
                    continue
                nconv = f"{A['n_conv']}/{A['n_total']}"
                if not A["n_conv"]:
                    a(f"\\num{{{lr:g}}} & \\texttt{{{v}}} & {{{nm}}} & {nconv}"
                      f" & {{--}} & {{--}} & {{diverged}} \\\\")
                    continue
                ppl = (f"\\num{{{A['ppl_mean']:.3f}}}"
                       + (f" (\\num{{{A['ppl_sem']:.3f}}})"
                          if A.get("ppl_sem") is not None else ""))
                rng = ("{--}" if "gap_min" not in A else
                       f"\\num{{{A['gap_min']:.3g}}}--"
                       f"\\num{{{A['gap_max']:.3g}}}")
                a(f"\\num{{{lr:g}}} & \\texttt{{{v}}} & {{{nm}}} & {nconv}"
                  f" & {ppl} & {_g(A.get('gap_median'))} & {rng} \\\\")
        a("\\midrule")
    L[-1] = "\\bottomrule"
    a("\\end{tabular}")
    _keys = [(2, 32, "fixnorm", lr) for lr in _lrs]
    _pc = CD.pooled_spread(ctrl, _keys)
    _pe = CD.pooled_spread(cert, _keys)
    if _pc and _pe:
        a("\\\\[2pt]\\footnotesize Pooled over all three learning rates, the "
          f"control's fixnorm gap spans \\num{{{_pc['min']:.3g}}} to "
          f"\\num{{{_pc['max']:.3g}}} (\\num{{{_pc['spread']:.0f}}}$\\times$, "
          f"$n={_pc['n']}$, of which {_pc['n_meaningful']} fall below the "
          f"\\num{{{CD.GAP_MEANINGFUL:.0g}}} informativeness threshold), while "
          f"the certified arm spans \\num{{{_pe['min']:.3g}}} to "
          f"\\num{{{_pe['max']:.3g}}} (\\num{{{_pe['spread']:.2f}}}$\\times$, "
          f"$n={_pe['n']}$, all {_pe['n_meaningful']} informative). The effect "
          "is a collapse of spread, not only of the median; the median ratio "
          "itself is withheld because its denominator is unstable.")
    a("\\end{table}")
    a("")

a("% No custom macros required: booktabs + siunitx only.")

open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print(f"wrote {OUT} ({len(L)} lines)")
