"""Generate C14_AUDIT.md from the audit JSONs, so its numbers cannot drift.

Same discipline as src/report.py: the document is a rendering of the run, never
a hand-written summary of it.
"""
import sys, os, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "C14_AUDIT.md")


def load(name):
    p = os.path.join(RES, name)
    return json.load(open(p)) if os.path.exists(p) else None


base = load("baseline.json")
aud = load("c14_audit.json")
z3r = load("c14_z3.json")
lns = load("c14_ln_sweep.json")

L = []
w = L.append

w("# c14 -- independent verification audit\n")
w("Generated by `audit/report_c14.py` from `results/c14_audit.json`, "
  "`results/c14_z3.json` and `results/c14_ln_sweep.json`. "
  "Methodology and caveats: `audit/README.md`.\n")

w("## 0. What this audit does and does not establish\n")
w("- It re-derives the prover's own box decomposition and confirms the replay "
  "reproduces `baseline.json`'s verdict at every radius.")
w("- It attacks each discharged box with dense sampling and PGD on the exact "
  "float64 model. No violation of a claimed bound was found.")
w("- It confirms the prover's **primitives** against z3 over exact rationals.")
w("- It does **not** provide an independent end-to-end sound bound. Both "
  "reference engines are vacuous on this model, for a measured reason "
  "(4.7e8 amplification through two blocks). That gap is real and stated.\n")

if aud:
    w("## 1. Replay, falsification and coverage\n")
    w("| rho | prover | baseline | agrees | discharged boxes | coverage | "
      "max true margin | max (true - bound) | IBP closed |")
    w("|---|---|---|---|---|---|---|---|---|")
    for r, v in aud["per_rho"].items():
        f, c, i = v["falsification"], v["coverage"], v["independent_ibp"]
        w(f"| {r} | {v['prover_proved']} | {v['baseline_claimed']} | "
          f"{v['replay_agrees_with_baseline']} | {v['discharged_boxes']} | "
          f"{c['random_point_coverage']:.4f} | "
          f"{f['max_true_margin_found']:+.4f} | "
          f"{f['max_true_minus_claimed_bound']:+.3e} | "
          f"{i['boxes_closed']}/{i['boxes_attempted']} |")
    w("")
    w(f"- **No unsoundness found:** `{aud['VERDICT']['no_unsoundness_found']}`. "
      "`max (true - bound)` is the largest amount by which any sampled point "
      "exceeded the bound claimed for its own box; it must stay negative.")
    w("- `coverage` is the fraction of 20k uniform points in `[-rho, rho]^4` "
      "that land in some discharged box. 1.0000 means the conjunction of "
      "per-box claims really does cover the whole threat set.")
    w("- `IBP closed` is the independent sound engine. It closes nothing "
      "anywhere; see `audit/README.md` Result 1.")
    w(f"\nRuntime {aud['runtime_sec']:.0f}s, "
      f"{aud['config']['samples_per_box']} samples/box plus "
      f"{aud['config']['pgd_steps']}-step PGD.\n")

if z3r:
    s = z3r["summary"]
    w("## 2. Exact SMT audit of the primitives\n")
    w(f"z3 {z3r['config']['z3_version']}, timeout "
      f"{z3r['config']['timeout_ms']}ms, at rho={z3r['config']['rho']}.\n")
    w("| check | expected | conclusive | passed |")
    w("|---|---|---|---|")
    ms, mt = s["margin_soundness"], s["margin_tightness"]
    w(f"| margin readout, soundness | unsat | {ms['conclusive']}/{ms['attempted']} "
      f"| {ms['passed']} |")
    w(f"| margin readout, tightness | sat | - | {mt['passed']}/{mt['attempted']} |")
    for k in ("relu", "layernorm"):
        t = s[k]
        w(f"| {k} containment | unsat | {t['conclusive']}/{t['attempted']} "
          f"| {t['passed']} |")
    w("")
    w("`unknown` is a solver timeout, never a refutation. The tightness query "
      "is the one that would have caught the patched `unsafe_margin_upper` bug: "
      "the buggy `max_u L_u - min_j L_j` is still a sound upper bound, so a "
      "soundness check passes on it. Only tightness sees the ~11.7-logit "
      "inflation.\n")

if lns:
    w("## 3. The LayerNorm attribution is backwards\n")
    w("| rho | margin bound | unstable ReLUs (L1.ln2) | LN spread (max) |")
    w("|---|---|---|---|")
    for row in lns["rows"]:
        s2 = [x for x in row["sites"] if x["layer"] == 1 and x["site"] == "ln2"][0]
        if row["rho"] < 2e-3 or row["rho"] > 3e-2:
            continue
        w(f"| {row['rho']:.5f} | {row['margin_bound']:+.3e} | "
          f"{s2['unstable_relus']}/{s2['of_total']} | "
          f"{s2['spread_ratio_max']:.3e} |")
    fz = lns["cliff"]["margin_bound_first_nonnegative_at_rho"]
    w("")
    w(f"The unsplit bound first goes non-negative at **rho = {fz:.5f}**, where the "
      "LayerNorm variance bracket is still essentially tight. The bracket only "
      "degrades an order of magnitude later, after the bound has already passed "
      "1e8. The unstable-ReLU count is the driver; the LayerNorm cliff is a "
      "downstream consequence.\n")
    w("Caveats: these are **unsplit** bounds (the certificate reaches rho=0.04 "
      "only because BaB splits into 2047 small boxes), and the bound is **not "
      "monotone** in rho because `promote_E_topk`/`compact` are radius-dependent "
      "heuristics.\n")

w("## 4. Corrections to the record\n")
w("Claims that circulated in summaries of this work and do not survive the "
  "artifacts:\n")
if base:
    mono = base["certification"]["monolithic_safety"]
    ab = base["certification"]["metric_ablation"]
    i0 = ab["icnn"]["0.005"]["layer0"]["stats"]["stats"]["worst"]
    q0 = ab["quadratic_only"]["0.005"]["layer0"]["stats"]["stats"]["worst"]
    i1 = ab["icnn"]["0.005"]["layer1"]["stats"]["stats"]["worst"]
    q1 = ab["quadratic_only"]["0.005"]["layer1"]["stats"]["stats"]["worst"]
    w(f"1. **The ICNN penalty is not 12x.** Measured BaB worst residuals at "
      f"gamma_hi=6: layer0 {i0:.4e} vs {q0:.4e} (**{i0/q0:.1f}x**), layer1 "
      f"{i1:.4e} vs {q1:.4e} (**{i1/q1:.1f}x**). More importantly *both* metrics "
      f"certified nothing -- every `gamma_certified` is null -- so 'the ICNN adds "
      f"no power over the quadratic' misleads: the quadratic did not work either.")
w("2. **The 250x conservativeness gap is not caused by the scale-invariance of "
  "`V(e')/V(e)`.** The gap is between the *monolithic margin* certificate "
  "(rho=0.04) and PGD (rho=10). `V` does not appear in that proof path at all; "
  "the margin obligation is additive, which is exactly why BaB closes it. "
  "Scale-invariance is what blocks the *growth-ratio* obligation, a different "
  "certificate that certified nothing. The two findings are independent.")
w("3. **Strict-decrease infeasibility is a measurement, not a theorem about "
  "transformers.** 'Strict decrease exists iff spectral radius < 1' is standard "
  "Lyapunov theory. What is new here is the measured value 1.273 on the "
  "certified subspace of *this* model -- a 2-layer, d_model=32, 26,144-parameter "
  "toy transformer on a synthetic routing task. It does not generalise to "
  "transformers as a class on this evidence.")
w("4. **The residual recursion is pre-LN with the MLP on the post-attention "
  "stream:** `x_{l+1} = x_l + Attn(LN(x_l)) + MLP(LN(x_l + Attn(LN(x_l))))`, not "
  "`x + Attn(x) + MLP(x)`.")
if aud:
    w("5. **The certificate is stated for a single prompt anchor** "
      "(`x_nom = trace[0][0]`), not over the prompt distribution.")

w("\n## 5. Remaining vulnerability\n")
w("`backends.independent_cross_check` should be read as *partially* closed:\n")
w("- primitives: confirmed against z3 over exact rationals;")
w("- end-to-end: **not** independently confirmed. Closing it needs a second "
  "correlation-preserving prover (CROWN/DeepPoly-style backward linear "
  "relaxation). Every decorrelating method is provably useless here.")

open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print(f"wrote {OUT} ({len(L)} lines)")
